/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 koi_cat.glb --tranform 
Author: radiergummi (https://sketchfab.com/radiergummi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koi-cat-216615de5f91404a90ba0a721e13dd36
Title: Koi Cat
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Cat(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/koi_cat.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="BezierCircle_1" position={[0, -0.548, 0]} />
              <group name="BezierCircle001_10" position={[0, -0.548, 0]} />
              <group name="Circle008_13" position={[0, 8.878, 0]} rotation={[0, 0.007, 0]} />
              <group name="Circle028_28" position={[-1.207, 0.604, 1.236]} rotation={[3.056, -0.859, 0.156]} scale={1.552}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Frog} />
              </group>
              <group name="Target_2_29" position={[0, 8.123, 0]} rotation={[0.001, 0, -0.05]} scale={[1.003, 1, 1.001]} />
              <group name="Target_2_2_30" position={[0, 7.992, 0]} rotation={[0.143, 0.172, 0.038]} scale={1.097} />
              <group name="fish_flow_35" position={[0, 4.446, 0]} scale={1.952}>
                <group name="Driver_fish_1_31" position={[-0.077, -2.278, -0.112]} rotation={[0, 0, -Math.PI / 2]} scale={0.111}>
                  <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_0} />
                </group>
                <group name="Driver_fish_2_32" position={[-0.077, -2.278, -0.112]} rotation={[0, 0, -Math.PI / 2]} scale={0.111}>
                  <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_0} />
                </group>
                <group name="fish_1_33" position={[-0.145, -2.708, -0.3]} rotation={[-Math.PI, 0.54, Math.PI]} scale={[-0.512, 0.512, 0.512]}>
                  <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Fish_Texture} />
                  <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Frog_2} />
                </group>
                <group name="fish_2_34" position={[0.164, -2.68, 0.306]} rotation={[0, -0.47, 0]} scale={[-0.512, 0.512, 0.512]}>
                  <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Fish_Texture} />
                  <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Frog_2} />
                </group>
              </group>
              <group name="Plane100_36" position={[0.513, 2.158, 0.211]} rotation={[-2.916, -0.464, 2.871]} scale={[0.588, 0.311, 0.529]}>
                <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Frog} />
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Frog} />
              </group>
              <group name="Plane071_37" position={[-1.294, -1.898, 0.211]} rotation={[-2.841, -0.209, -2.684]} scale={[0.426, 0.225, 0.383]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Frog} />
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Frog} />
              </group>
              <group name="Plane117_38" position={[1.149, 2.006, 0.016]} rotation={[0, 0, 1.303]} scale={0.09}>
                <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Frog} />
              </group>
              <group name="Plane119_39" position={[1.548, 1.718, 0.016]} rotation={[-0.35, 0.019, 0.507]} scale={0.657}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Frog} />
              </group>
              <group name="Plane120_40" position={[1.799, 1.132, 0.016]} rotation={[-3.065, -0.094, -2.977]} scale={[0.103, 0.102, 0.103]}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Frog} />
              </group>
              <group name="Plane122_41" position={[-1.896, -1.42, 0.016]} rotation={[3, -0.182, 1.972]} scale={0.682}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Frog} />
              </group>
              <group name="Plane123_42" position={[-2.14, -0.946, -0.418]} rotation={[-0.62, 0.386, 0.938]} scale={[0.132, 0.133, 0.132]}>
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Frog} />
              </group>
              <group name="Ears_83" position={[-0.083, 0.565, 0.437]}>
                <group name="GLTF_created_6">
                  <primitive object={nodes.GLTF_created_6_rootJoint} />
                  <group name="Cube004_82" />
                  <skinnedMesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.Frog} skeleton={nodes.Object_134.skeleton} />
                  <skinnedMesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.Frog_2} skeleton={nodes.Object_135.skeleton} />
                </group>
              </group>
              <group name="Plane_84" position={[-0.05, -0.067, 0.096]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Frog} />
              </group>
              <group name="Cube011_85" position={[-0.052, -0.067, 0.095]}>
                <mesh name="mesh_38" geometry={nodes.mesh_38.geometry} material={materials.Frog} morphTargetDictionary={nodes.mesh_38.morphTargetDictionary} morphTargetInfluences={nodes.mesh_38.morphTargetInfluences} />
              </group>
              <group name="Cube012_86" position={[-0.052, -0.067, 0.095]}>
                <mesh name="mesh_39" geometry={nodes.mesh_39.geometry} material={materials.Frog} morphTargetDictionary={nodes.mesh_39.morphTargetDictionary} morphTargetInfluences={nodes.mesh_39.morphTargetInfluences} />
              </group>
              <group name="Cube013_87" position={[-0.052, -0.067, 0.095]}>
                <mesh name="mesh_40" geometry={nodes.mesh_40.geometry} material={materials.Frog} morphTargetDictionary={nodes.mesh_40.morphTargetDictionary} morphTargetInfluences={nodes.mesh_40.morphTargetInfluences} />
              </group>
              <group name="Cube014_88" position={[-0.052, -0.067, 0.095]}>
                <mesh name="mesh_41" geometry={nodes.mesh_41.geometry} material={materials.Frog} morphTargetDictionary={nodes.mesh_41.morphTargetDictionary} morphTargetInfluences={nodes.mesh_41.morphTargetInfluences} />
              </group>
              <group name="Circle013_89" position={[-0.052, -0.067, 0.095]}>
                <mesh name="mesh_42" geometry={nodes.mesh_42.geometry} material={materials.Frog} morphTargetDictionary={nodes.mesh_42.morphTargetDictionary} morphTargetInfluences={nodes.mesh_42.morphTargetInfluences} />
              </group>
              <group name="Plane045_91" position={[-0.005, -0.157, 0.007]} rotation={[2.928, -0.764, 2.964]} scale={[1.218, 0.644, 1.523]}>
                <group name="Plane046_90">
                  <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.Frog} />
                </group>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Frog} />
              </group>
              <group name="Plane059_93" position={[0.149, -0.173, 0.182]} rotation={[2.728, -0.766, 2.922]} scale={[1.218, 0.644, 1.096]}>
                <group name="Plane060_92">
                  <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.Frog} />
                </group>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.Frog} />
              </group>
              <group name="Circle_94" position={[-0.596, 2.266, 0.298]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.White} />
              </group>
              <group name="Circle001_95" position={[-2.096, 0.595, 0.089]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.White} />
              </group>
              <group name="Circle002_96" position={[-2.356, 0.365, 0.74]} scale={[0.815, 0.849, 1]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.White} />
              </group>
              <group name="Circle005_97" position={[1.762, -1.151, -0.056]} scale={[0.815, 0.849, 0.686]}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.White} />
              </group>
              <group name="Circle006_98" position={[1.517, -1.594, -0.056]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.White} />
              </group>
              <group name="Circle027_99" position={[1.056, -1.727, -0.056]} rotation={[0, 0, -Math.PI]} scale={[0.01, 0.01, 1]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.White} />
              </group>
              <group name="Circle029_100" position={[-1.442, -1.564, -0.056]} rotation={[0, 0, -Math.PI]} scale={[0.01, 0.01, 1]}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.White} />
              </group>
              <group name="Circle030_101" position={[-1.54, -2.186, -0.056]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.White} />
              </group>
              <group name="Circle031_102" position={[-0.838, -1.945, -0.056]} rotation={[0, 0, -Math.PI]} scale={[0.01, 0.01, 1]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.White} />
              </group>
              <group name="Circle032_103" position={[-0.046, 2.394, -0.104]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.White} />
              </group>
              <group name="Circle033_104" position={[0.866, 1.904, -0.056]} scale={[0.815, 0.849, 1]}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.White} />
              </group>
              <group name="Circle034_105" position={[-0.016, -0.639, 1.735]} rotation={[0, 0, -Math.PI]} scale={[0.01, 0.01, 1]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.White} />
              </group>
              <group name="Circle035_106" position={[0.718, -0.158, 1.735]} scale={[0.815, 0.849, 1]}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.White} />
              </group>
              <group name="Circle036_107" position={[-0.521, -0.534, 1.735]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.White} />
              </group>
              <group name="Circle037_108" position={[2.057, 1.189, -0.056]} rotation={[0, 0, -Math.PI]} scale={[0.01, 0.01, 1]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.White} />
              </group>
              <group name="Circle038_109" position={[1.845, 0.694, -0.056]} scale={[0.965, 1.038, 1]}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.White} />
              </group>
              <group name="Plane058_2">
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Frog} />
              </group>
              <group name="Armature002_9" position={[0.138, 0.128, -0.739]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Torus007_8" />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Frog} skeleton={nodes.Object_10.skeleton} />
                </group>
              </group>
              <group name="Cube003_11" position={[0.018, 0.027, 0.004]} rotation={[0, -0.228, 0]} scale={0.393}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Frog} />
              </group>
              <group name="Cube007_12" position={[0.018, 0.027, 0.004]} rotation={[0, -0.228, 0]} scale={0.412}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Frog} />
              </group>
              <group name="Cube_14" scale={0.983}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Frog} />
              </group>
              <group name="Cube001_15" scale={0.994}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Frog} />
              </group>
              <group name="Cube002_16" scale={0.99}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Frog} />
              </group>
              <group name="Cube005_17" scale={[0.927, 0.929, 0.927]}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Frog} />
              </group>
              <group name="Cube006_18" scale={[0.927, 0.929, 0.927]}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Frog} />
              </group>
              <group name="Cylinder001_19" position={[-1.328, 1.271, 0.485]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Frog} />
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.White} />
              </group>
              <group name="Cylinder003_20" position={[-1.604, 1.527, 0.593]} rotation={[-0.043, 0.357, 0.841]} scale={0.846}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Frog} />
              </group>
              <group name="Sphere_23" rotation={[0, -0.44, 0]} scale={[-1.631, 1.631, 1.631]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Frog} />
              </group>
              <group name="Torus002_25" position={[-1.175, 1.118, 0.423]} rotation={[-0.048, 0.381, 0.842]} scale={0.63}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Frog} />
              </group>
              <group name="Torus004_26" position={[-1.194, 0.889, 1]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Frog} />
              </group>
              <group name="Torus005_27" position={[-1.218, 0.717, 1.155]} rotation={[1.065, -0.595, -2.909]} scale={0.143}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Frog} />
              </group>
              <group name="Circle025_43" position={[-0.477, -0.131, -1.007]} rotation={[-2.557, -0.785, -2.664]}>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Frog} />
              </group>
              <group name="Circle026_44" position={[-0.477, -0.131, -1.007]} rotation={[-2.557, -0.785, -2.664]}>
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Frog} />
              </group>
              <group name="Cylinder020_45" position={[-0.475, -1.049, -0.988]} rotation={[0, 1.448, 0]} scale={[0.373, 0.293, 0.373]}>
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Frog_2} />
              </group>
              <group name="Cylinder021_46" position={[-0.475, -1.049, -0.988]} rotation={[0, 1.448, 0]} scale={[0.373, 0.293, 0.373]}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Frog_2} />
              </group>
              <group name="Lotos_3_52" position={[0.55, -0.064, -0.869]}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="Lotos)3_51" />
                  <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Frog} skeleton={nodes.Object_88.skeleton} />
                </group>
              </group>
              <group name="Lotos_2_58" position={[-0.149, -0.064, -1.029]}>
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="Cylinder015_57" />
                  <skinnedMesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.Frog} skeleton={nodes.Object_97.skeleton} />
                </group>
              </group>
              <group name="Lotos_1_64" position={[-1.056, -0.118, -0.271]} rotation={[-Math.PI, 0.326, -Math.PI]}>
                <group name="GLTF_created_3">
                  <primitive object={nodes.GLTF_created_3_rootJoint} />
                  <group name="Lotos_1001_63" />
                  <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Frog} skeleton={nodes.Object_106.skeleton} />
                  <skinnedMesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Frog} skeleton={nodes.Object_107.skeleton} />
                </group>
              </group>
              <group name="Lotos_4_70" position={[1.081, -0.064, -0.48]}>
                <group name="GLTF_created_4">
                  <primitive object={nodes.GLTF_created_4_rootJoint} />
                  <group name="Cylinder012_69" />
                  <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.Frog} skeleton={nodes.Object_116.skeleton} />
                </group>
              </group>
              <group name="Lotos_5_76" position={[0.32, -1.502, -0.081]} scale={0.765}>
                <group name="GLTF_created_5">
                  <primitive object={nodes.GLTF_created_5_rootJoint} />
                  <group name="Lotos_5001_75" />
                  <skinnedMesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.Frog_2} skeleton={nodes.Object_125.skeleton} />
                </group>
              </group>
              <group name="Curve059_110" position={[-0.045, -0.147, 0.008]} scale={21.479}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.Frog} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/koi_cat.glb')
